#!/bin/sh

set -e

cd bin

zig cc -Os ../exe2gui.c -o exe2gui

zig cc -Os -target x86-windows-gnu ../windows.c -o run.wx32.exe
zig cc -Os -target x86_64-windows-gnu ../windows.c -o run.wx64.exe
zig cc -Os -target aarch64-windows-gnu ../windows.c -o run.wa64.exe
cp run.wx32.exe runw.wx32.exe
cp run.wx64.exe runw.wx64.exe
cp run.wa64.exe runw.wa64.exe
./exe2gui runw.wx32.exe
./exe2gui runw.wx64.exe
./exe2gui runw.wa64.exe
rm -f exe2gui

do_lin_build() {
	set -e
	zig cc -Os -DTRICKERY -target $1 ../unix.c -o $2
	patchelf --clear-symbol-version __libc_start_main $2
	patchelf --clear-symbol-version strlen $2
	patchelf --clear-symbol-version strdup $2
	patchelf --clear-symbol-version realloc $2
	patchelf --clear-symbol-version dlopen $2
	patchelf --clear-symbol-version dlsym $2
	patchelf --clear-symbol-version free $2
	patchelf --clear-symbol-version stderr $2
	patchelf --clear-symbol-version fprintf $2
	patchelf --clear-symbol-version exit $2
	patchelf --clear-symbol-version abort $2
}

do_lin_build x86-linux-gnu run.lgx32
do_lin_build x86_64-linux-gnu run.lgx64
do_lin_build aarch64-linux-gnu run.lga64
do_lin_build riscv64-linux-gnu run.lgr64

zig cc -Os -DMAC -target x86_64-macos ../unix.c -o run.mx64
zig cc -Os -DMAC -target aarch64-macos ../unix.c -o run.ma64

# program
zig cc -shared -s -target x86-windows-gnu ../example.c -o run.wx32.dll
zig cc -shared -s -target x86_64-windows-gnu ../example.c -o run.wx64.dll
zig cc -shared -s -target aarch64-windows-gnu ../example.c -o run.wa64.dll

zig cc -Os -shared -target x86-linux-gnu ../example.c -o run.lgx32.so
zig cc -Os -shared -target x86_64-linux-gnu ../example.c -o run.lgx64.so
zig cc -Os -shared -target aarch64-linux-gnu ../example.c -o run.lga64.so
zig cc -Os -shared -target riscv64-linux-gnu ../example.c -o run.lgr64.so

zig cc -Os -DMAC -shared -target x86_64-macos ../example.c -o run.mx64.dylib
zig cc -Os -DMAC -shared -target aarch64-macos ../example.c -o run.ma64.dylib
