#!/bin/sh

set -e

cd bin

rm -f run*

# egor-tensin/setup-mingw does what we want it to do, but sets -posix without asking.
# We don't want that, so be explicit.
W32GCC=i686-w64-mingw32-gcc-win32
W64GCC=x86_64-w64-mingw32-gcc-win32

$W32GCC -s -Os ../windows.c -o run.wx32.exe
$W64GCC -s -Os ../windows.c -o run.wx64.exe
$W32GCC -s -mwindows -Os ../windows.c -o runw.wx32.exe
$W64GCC -s -mwindows -Os ../windows.c -o runw.wx64.exe

zig cc -Os ../exe2gui.c -o exe2gui
zig cc -Os -target aarch64-windows-gnu ../windows.c -o run.wa64.exe
cp run.wa64.exe runw.wa64.exe
./exe2gui runw.wa64.exe
rm -f exe2gui

do_lin_build() {
	set -e
	zig cc -Os -DTRICKERY -target $1 ../unix.c -o $2
	patchelf --clear-symbol-version __libc_start_main $2
	patchelf --clear-symbol-version strlen $2
	patchelf --clear-symbol-version strdup $2
	patchelf --clear-symbol-version realloc $2
	patchelf --clear-symbol-version dlopen $2
	patchelf --clear-symbol-version dlsym $2
	patchelf --clear-symbol-version free $2
	patchelf --clear-symbol-version stderr $2
	patchelf --clear-symbol-version fprintf $2
	patchelf --clear-symbol-version exit $2
	patchelf --clear-symbol-version abort $2
}

do_lin_build x86-linux-gnu run.lgx32
do_lin_build x86_64-linux-gnu run.lgx64
do_lin_build aarch64-linux-gnu run.lga64
do_lin_build riscv64-linux-gnu run.lgr64

zig cc -Os -DMAC -target x86_64-macos ../unix.c -o run.mx64
zig cc -Os -DMAC -target aarch64-macos ../unix.c -o run.ma64

# program
$W32GCC -shared -s ../example.c -o run.wx32.dll
$W64GCC -shared -s ../example.c -o run.wx64.dll
zig cc -shared -s -target aarch64-windows-gnu ../example.c -o run.wa64.dll

zig cc -Os -shared -target x86-linux-gnu ../example.c -o run.lgx32.so
zig cc -Os -shared -target x86_64-linux-gnu ../example.c -o run.lgx64.so
zig cc -Os -shared -target aarch64-linux-gnu ../example.c -o run.lga64.so
zig cc -Os -shared -target riscv64-linux-gnu ../example.c -o run.lgr64.so

zig cc -Os -DMAC -shared -target x86_64-macos ../example.c -o run.mx64.dylib
zig cc -Os -DMAC -shared -target aarch64-macos ../example.c -o run.ma64.dylib

# clean up
cd ..

rm -f solaunch.zip
zip -q -r solaunch.zip bin COPYING README.md *.c
